package app.agro.samruddhi.ui.theme

import androidx.compose.ui.graphics.Color

object Palette {

    val md_theme_light_primary = Color(0xFF006E2C)
    val md_theme_light_onPrimary = Color(0xFFFFFFFF)
    val md_theme_light_primaryContainer = Color(0xFF89FA9B)
    val md_theme_light_onPrimaryContainer = Color(0xFF002108)
    val md_theme_light_secondary = Color(0xFF016D38)
    val md_theme_light_onSecondary = Color(0xFFFFFFFF)
    val md_theme_light_secondaryContainer = Color(0xFF9BF6B2)
    val md_theme_light_onSecondaryContainer = Color(0xFF00210D)
    val md_theme_light_tertiary = Color(0xFFAA3615)
    val md_theme_light_onTertiary = Color(0xFFFFFFFF)
    val md_theme_light_tertiaryContainer = Color(0xFFFFDBD1)
    val md_theme_light_onTertiaryContainer = Color(0xFF3B0800)
    val md_theme_light_error = Color(0xFFBA1A1A)
    val md_theme_light_errorContainer = Color(0xFFFFDAD6)
    val md_theme_light_onError = Color(0xFFFFFFFF)
    val md_theme_light_onErrorContainer = Color(0xFF410002)
    val md_theme_light_background = Color(0xFFFFFBFF)
    val md_theme_light_onBackground = Color(0xFF2A1800)
    val md_theme_light_surface = Color(0xFFFFFBFF)
    val md_theme_light_onSurface = Color(0xFF2A1800)
    val md_theme_light_surfaceVariant = Color(0xFFDDE5D9)
    val md_theme_light_onSurfaceVariant = Color(0xFF424940)
    val md_theme_light_outline = Color(0xFF727970)
    val md_theme_light_inverseOnSurface = Color(0xFFFFEEDE)
    val md_theme_light_inverseSurface = Color(0xFF462A00)
    val md_theme_light_inversePrimary = Color(0xFF6DDD81)
    val md_theme_light_shadow = Color(0xFF000000)
    val md_theme_light_surfaceTint = Color(0xFF006E2C)
    val md_theme_light_outlineVariant = Color(0xFFC1C9BE)
    val md_theme_light_scrim = Color(0xFF000000)

    val md_theme_dark_primary = Color(0xFF6DDD81)
    val md_theme_dark_onPrimary = Color(0xFF003914)
    val md_theme_dark_primaryContainer = Color(0xFF005320)
    val md_theme_dark_onPrimaryContainer = Color(0xFF89FA9B)
    val md_theme_dark_secondary = Color(0xFF80D998)
    val md_theme_dark_onSecondary = Color(0xFF00391A)
    val md_theme_dark_secondaryContainer = Color(0xFF005228)
    val md_theme_dark_onSecondaryContainer = Color(0xFF9BF6B2)
    val md_theme_dark_tertiary = Color(0xFFFFB5A1)
    val md_theme_dark_onTertiary = Color(0xFF601300)
    val md_theme_dark_tertiaryContainer = Color(0xFF881F00)
    val md_theme_dark_onTertiaryContainer = Color(0xFFFFDBD1)
    val md_theme_dark_error = Color(0xFFFFB4AB)
    val md_theme_dark_errorContainer = Color(0xFF93000A)
    val md_theme_dark_onError = Color(0xFF690005)
    val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
    val md_theme_dark_background = Color(0xFF2A1800)
    val md_theme_dark_onBackground = Color(0xFFFFDDB6)
    val md_theme_dark_surface = Color(0xFF2A1800)
    val md_theme_dark_onSurface = Color(0xFFFFDDB6)
    val md_theme_dark_surfaceVariant = Color(0xFF424940)
    val md_theme_dark_onSurfaceVariant = Color(0xFFC1C9BE)
    val md_theme_dark_outline = Color(0xFF8B9389)
    val md_theme_dark_inverseOnSurface = Color(0xFF2A1800)
    val md_theme_dark_inverseSurface = Color(0xFFFFDDB6)
    val md_theme_dark_inversePrimary = Color(0xFF006E2C)
    val md_theme_dark_shadow = Color(0xFF000000)
    val md_theme_dark_surfaceTint = Color(0xFF6DDD81)
    val md_theme_dark_outlineVariant = Color(0xFF424940)
    val md_theme_dark_scrim = Color(0xFF000000)


    val seed = Color(0xFF34A853)
    val Orange00 = Color(0xFFFE724C)
    val CustomColor2 = Color(0xFFFFBA49)
    val light_Orange00 = Color(0xFFAA3615)
    val light_onOrange00 = Color(0xFFFFFFFF)
    val light_Orange00Container = Color(0xFFFFDBD1)
    val light_onOrange00Container = Color(0xFF3B0800)
    val dark_Orange00 = Color(0xFFFFB5A1)
    val dark_onOrange00 = Color(0xFF601300)
    val dark_Orange00Container = Color(0xFF881F00)
    val dark_onOrange00Container = Color(0xFFFFDBD1)
    val light_CustomColor2 = Color(0xFF805600)
    val light_onCustomColor2 = Color(0xFFFFFFFF)
    val light_CustomColor2Container = Color(0xFFFFDDB0)
    val light_onCustomColor2Container = Color(0xFF291800)
    val dark_CustomColor2 = Color(0xFFFFBA49)
    val dark_onCustomColor2 = Color(0xFF442B00)
    val dark_CustomColor2Container = Color(0xFF614000)
    val dark_onCustomColor2Container = Color(0xFFFFDDB0)

}